#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue May 27 08:11:03 EDT 2025
# SW Build 5076996 on Wed May 22 18:36:09 MDT 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tinyrisc_mac_tb_behav -key {Behavioral:sim_1:Functional:tinyrisc_mac_tb} -tclbatch tinyrisc_mac_tb.tcl -log simulate.log"
xsim tinyrisc_mac_tb_behav -key {Behavioral:sim_1:Functional:tinyrisc_mac_tb} -tclbatch tinyrisc_mac_tb.tcl -log simulate.log

