RISCV_ARCH := rv32im_zicsr
RISCV_ABI := ilp32
RISCV_MCMODEL := medlow


TARGET = uart_tx


#CFLAGS += -DSIMULATION
#CFLAGS += -O2
#ASM_SRCS +=
#LDFLAGS +=
#INCLUDES += -I.

C_SRCS := \
	main.c \


COMMON_DIR = ..
TOOLCHAIN_DIR = /opt/riscv32im
include ../common.mk
